name: Elpris 1H Updater

on:
  schedule:
    - cron: '5 3 * * *'  # Varje dag kl 03:05
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run elpris_1h.py
        env:
          GIST_ID: ${{ secrets.GIST_ID_1H }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN_1H }}
        run: python elpris_1h.py
