name: Keep Repository Active (No Push)

on:
  schedule:
    - cron: '0 2 * * 0'  # Kör varje söndag kl 02:00
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp (no push)
        run: echo "Keepalive run at $(date)" > /dev/null

